<a href="https://colab.research.google.com/github/MinGyunKim27/Calc/blob/main/dot_production.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('sample_data.csv')


In [39]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [40]:
data

movieId                        title era  \
0           1                    Toy Story   B   
1           2                      Jumanji   B   
2           3             Grumpier Old Men   B   
3           5  Father of the Bride Part II   B   
4           7                      Sabrina   B   
...       ...                          ...  ..   
1567   183611                   Game Night   C   
1568   184471                  Tomb Raider   C   
1569   187593                   Deadpool 2   C   
1570   187595      Solo: A Star Wars Story   C   
1571   193565           Gintama: The Movie   C   

                                                 genres  \
0     [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, ...   
1     [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
...                                                 ...   
1567  [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
1568  [0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1569  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
1570  [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1571  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   

                                                    tag  \
0     [-0.80688363  0.34333864 -1.634787    0.827779...   
1     [-1.062782    1.2268646  -1.6137172  -0.900875...   
2     [-0.87365466  0.5569652   0.14252552 -0.952937...   
3     [ 0.32481757  0.42620605  0.6798344   0.193016...   
4     [-0.04015052  0.76239765  0.11476712  0.045612...   
...                                                 ...   
1567  [-1.6250098   0.23257312  0.5173523   0.326692...   
1568  [-1.695522    0.04618992 -2.1467805  -0.473268...   
1569  [ 0.88472164  1.5220832  -0.38778797 -1.777470...   
1570  [-0.2595632   0.7533516   0.29786414 -1.240825...   
1571  [ 0.03698341  0.32170403  0.73136777 -0.701852...   

                                                  story   runtime  \
0     [-0.02615408 -0.02989563 -0.04940377  0.042764...  0.983654   
1     [-0.01884955  0.01303691 -0.02845779  0.013103...  0.395233   
2     [-0.0102846  -0.03615021  0.020923   -0.042871...  0.333487   
3     [ 0.01457734  0.04639842  0.02174928 -0.020997...  0.821307   
4     [ 0.04174178  0.02333958 -0.04705052 -0.001693...  0.574440   
...                                                 ...       ...   
1567  [ 0.01328952 -0.04064459 -0.03820703  0.041445...  0.235612   
1568  [-0.02210807 -0.0079866  -0.0362287   0.002445...  0.002260   
1569  [ 0.04306086  0.00616845 -0.02693363  0.031448...  0.277788   
1570  [ 0.04268283 -0.04014726  0.03714632 -0.048184...  0.584240   
1571  [ 0.04851753 -0.01649501 -0.0428407   0.048739...  0.363594   

               director season  
0     Christopher Nolan    Win  
1     Christopher Nolan    Spr  
2     Christopher Nolan    Spr  
3     Christopher Nolan    Aut  
4     Christopher Nolan    Aut  
...                 ...    ...  
1567  Christopher Nolan    Win  
1568  Christopher Nolan    Spr  
1569  Christopher Nolan    Win  
1570  Christopher Nolan    Spr  
1571  Christopher Nolan    Spr  

[1572 rows x 9 columns]

In [41]:
title = data['title']

##개행문자 제거

In [42]:
# 'story' 열의 각 행에서 개행문자 제거
data['story'] = data['story'].str.replace('\n', '')


In [43]:
# 'story' 열의 각 행에서 개행문자 제거
data['tag'] = data['tag'].str.replace('\n', '')


## 스토리 원 닷

In [44]:
data['story'] = data['story'].apply(lambda story_str: np.array([float(num) for num in story_str.strip('[]').split(' ') if num]))


# 'story' 열의 값을 2차원 배열로 변환
story_array = np.vstack(data['story'].values)

# 코사인 유사도 계산
cosine_sim_story = cosine_similarity(story_array, story_array)

# 유사도 행렬 출력
print(cosine_sim_story)

[[ 1.          0.26440797 -0.1339712  ...  0.01884014 -0.08718575
  -0.06553231]
 [ 0.26440797  1.          0.31379784 ... -0.0710417  -0.11550634
   0.37025767]
 [-0.1339712   0.31379784  1.         ... -0.43150457  0.26425451
  -0.07289933]
 ...
 [ 0.01884014 -0.0710417  -0.43150457 ...  1.         -0.27280479
   0.30013459]
 [-0.08718575 -0.11550634  0.26425451 ... -0.27280479  1.
   0.12224381]
 [-0.06553231  0.37025767 -0.07289933 ...  0.30013459  0.12224381
   1.        ]]


In [45]:
# 영화-영화 유저관람 내역에 대한 유사도
movie_similarity_story = pd.DataFrame(cosine_sim_story,
                                index=title, columns=title)
print(movie_similarity_story.shape)
movie_similarity_story.head()

(1572, 1572)


title                        Toy Story   Jumanji  Grumpier Old Men  \
title                                                                
Toy Story                     1.000000  0.264408         -0.133971   
Jumanji                       0.264408  1.000000          0.313798   
Grumpier Old Men             -0.133971  0.313798          1.000000   
Father of the Bride Part II  -0.370172  0.205240          0.330004   
Sabrina                      -0.138107  0.284042          0.211590   

title                        Father of the Bride Part II   Sabrina  \
title                                                                
Toy Story                                      -0.370172 -0.138107   
Jumanji                                         0.205240  0.284042   
Grumpier Old Men                                0.330004  0.211590   
Father of the Bride Part II                     1.000000  0.433907   
Sabrina                                         0.433907  1.000000   

title                        American President, The     Nixon    Casino  \
title                                                                      
Toy Story                                  -0.015268  0.289825 -0.322833   
Jumanji                                    -0.040770  0.206989  0.202136   
Grumpier Old Men                           -0.037022 -0.263080 -0.168534   
Father of the Bride Part II                -0.068716 -0.185407  0.216164   
Sabrina                                    -0.180191 -0.106602  0.533415   

title                        Sense and Sensibility  Get Shorty  ...  \
title                                                           ...   
Toy Story                                -0.085415   -0.298138  ...   
Jumanji                                   0.126724   -0.101269  ...   
Grumpier Old Men                         -0.057542   -0.155010  ...   
Father of the Bride Part II              -0.062644   -0.102523  ...   
Sabrina                                  -0.233487    0.377154  ...   

title                        Blade Runner 2049   Mother!  \
title                                                      
Toy Story                             0.144562  0.189882   
Jumanji                              -0.242079  0.309368   
Grumpier Old Men                     -0.230505 -0.129569   
Father of the Bride Part II          -0.442911 -0.153861   
Sabrina                              -0.560173  0.096514   

title                        Jumanji: Welcome to the Jungle  \
title                                                         
Toy Story                                          0.160414   
Jumanji                                           -0.046642   
Grumpier Old Men                                   0.084578   
Father of the Bride Part II                        0.069694   
Sabrina                                            0.063987   

title                        The Shape of Water  The Greatest Showman  \
title                                                                   
Toy Story                             -0.297726              0.194216   
Jumanji                                0.197180              0.121926   
Grumpier Old Men                       0.308952             -0.142204   
Father of the Bride Part II            0.207864              0.157938   
Sabrina                                0.371479             -0.049412   

title                        Game Night  Tomb Raider  Deadpool 2  \
title                                                              
Toy Story                      0.151850     0.250451    0.018840   
Jumanji                       -0.069769     0.092043   -0.071042   
Grumpier Old Men               0.031344     0.291181   -0.431505   
Father of the Bride Part II   -0.209736    -0.075668    0.164153   
Sabrina                        0.194667     0.077193    0.341144   

title                        Solo: A Star Wars Story  Gintama: The Movie  
title                                                       

##태그 원 닷

In [46]:

# 'tag' 열의 각 행을 벡터로 변환하여 NumPy 배열로 만들기
data['tag'] = data['tag'].apply(lambda story_str: np.array([float(num) for num in story_str.strip('[]').split(' ') if num]))

# 'tag' 열의 값을 2차원 배열로 변환
tag_array = np.vstack(data['tag'].values)

# 코사인 유사도 계산
cosine_sim_tag = cosine_similarity(tag_array, tag_array)

# 유사도 행렬 출력
print(cosine_sim_tag)

[[1.         0.29503455 0.38746833 ... 0.29496455 0.31996136 0.1069249 ]
 [0.29503455 1.         0.59538992 ... 0.23239934 0.51083371 0.44532167]
 [0.38746833 0.59538992 1.         ... 0.19024972 0.19234335 0.39697482]
 ...
 [0.29496455 0.23239934 0.19024972 ... 1.         0.47779682 0.30352976]
 [0.31996136 0.51083371 0.19234335 ... 0.47779682 1.         0.5749375 ]
 [0.1069249  0.44532167 0.39697482 ... 0.30352976 0.5749375  1.        ]]


In [47]:
# 영화-영화 유저관람 내역에 대한 유사도
movie_similarity_tag = pd.DataFrame(cosine_sim_tag,
                                index=title, columns=title)
print(movie_similarity_tag.shape)
movie_similarity_tag.head()

(1572, 1572)


title                        Toy Story   Jumanji  Grumpier Old Men  \
title                                                                
Toy Story                     1.000000  0.295035          0.387468   
Jumanji                       0.295035  1.000000          0.595390   
Grumpier Old Men              0.387468  0.595390          1.000000   
Father of the Bride Part II   0.248902  0.379945          0.379666   
Sabrina                       0.336731  0.565760          0.462012   

title                        Father of the Bride Part II   Sabrina  \
title                                                                
Toy Story                                       0.248902  0.336731   
Jumanji                                         0.379945  0.565760   
Grumpier Old Men                                0.379666  0.462012   
Father of the Bride Part II                     1.000000  0.924424   
Sabrina                                         0.924424  1.000000   

title                        American President, The     Nixon    Casino  \
title                                                                      
Toy Story                                   0.454008  0.447721  0.587510   
Jumanji                                     0.449599  0.430883  0.456053   
Grumpier Old Men                            0.270719  0.259206  0.284119   
Father of the Bride Part II                 0.323799  0.314874  0.525102   
Sabrina                                     0.370537  0.356346  0.582013   

title                        Sense and Sensibility  Get Shorty  ...  \
title                                                           ...   
Toy Story                                 0.323145    0.523154  ...   
Jumanji                                   0.362542    0.469696  ...   
Grumpier Old Men                          0.426605    0.571783  ...   
Father of the Bride Part II               0.328170    0.736502  ...   
Sabrina                                   0.307072    0.753059  ...   

title                        Blade Runner 2049   Mother!  \
title                                                      
Toy Story                             0.550985  0.483042   
Jumanji                               0.384007  0.510068   
Grumpier Old Men                      0.205994  0.286501   
Father of the Bride Part II           0.141878  0.248869   
Sabrina                               0.301272  0.342100   

title                        Jumanji: Welcome to the Jungle  \
title                                                         
Toy Story                                          0.440210   
Jumanji                                            0.135575   
Grumpier Old Men                                   0.201422   
Father of the Bride Part II                        0.322216   
Sabrina                                            0.205803   

title                        The Shape of Water  The Greatest Showman  \
title                                                                   
Toy Story                              0.314889              0.574781   
Jumanji                                0.536629              0.450127   
Grumpier Old Men                       0.296339              0.533810   
Father of the Bride Part II            0.278047              0.191299   
Sabrina                                0.447935              0.264360   

title                        Game Night  Tomb Raider  Deadpool 2  \
title                                                              
Toy Story                      0.426515     0.367585    0.294965   
Jumanji                        0.210297     0.746083    0.232399   
Grumpier Old Men               0.447191     0.550556    0.190250   
Father of the Bride Part II    0.476674     0.358058    0.567816   
Sabrina                        0.371568     0.455993    0.441937   

title                        Solo: A Star Wars Story  Gintama: The Movie  
title                                                       

##장르 원 닷

In [48]:

# 'genres' 열의 각 행을 벡터로 변환하여 NumPy 배열로 만들기
data['genres'] = data['genres'].apply(lambda genre_list: np.array([int(num) for num in genre_list.strip('[]').split(',')]))

# 'genres' 열의 값을 2차원 배열로 변환
genres_array = np.vstack(data['genres'].values)

# 코사인 유사도 계산
cosine_sim = cosine_similarity(genres_array, genres_array)

# 유사도 행렬 출력
print(cosine_sim)

[[1.         0.77459667 0.31622777 ... 0.25819889 0.4472136  0.4472136 ]
 [0.77459667 1.         0.         ... 0.         0.57735027 0.        ]
 [0.31622777 0.         1.         ... 0.40824829 0.         0.35355339]
 ...
 [0.25819889 0.         0.40824829 ... 1.         0.57735027 0.8660254 ]
 [0.4472136  0.57735027 0.         ... 0.57735027 1.         0.5       ]
 [0.4472136  0.         0.35355339 ... 0.8660254  0.5        1.        ]]


In [49]:
# 영화-영화 유저관람 내역에 대한 유사도
movie_similarity_genre = pd.DataFrame(cosine_sim,
                                index=title, columns=title)
print(movie_similarity_genre.shape)
movie_similarity_genre.head()

(1572, 1572)


title                        Toy Story   Jumanji  Grumpier Old Men  \
title                                                                
Toy Story                     1.000000  0.774597          0.316228   
Jumanji                       0.774597  1.000000          0.000000   
Grumpier Old Men              0.316228  0.000000          1.000000   
Father of the Bride Part II   0.447214  0.000000          0.707107   
Sabrina                       0.316228  0.000000          1.000000   

title                        Father of the Bride Part II   Sabrina  \
title                                                                
Toy Story                                       0.447214  0.316228   
Jumanji                                         0.000000  0.000000   
Grumpier Old Men                                0.707107  1.000000   
Father of the Bride Part II                     1.000000  0.707107   
Sabrina                                         0.707107  1.000000   

title                        American President, The  Nixon  Casino  \
title                                                                 
Toy Story                                   0.258199    0.0     0.0   
Jumanji                                     0.000000    0.0     0.0   
Grumpier Old Men                            0.816497    0.0     0.0   
Father of the Bride Part II                 0.577350    0.0     0.0   
Sabrina                                     0.816497    0.0     0.0   

title                        Sense and Sensibility  Get Shorty  ...  \
title                                                           ...   
Toy Story                                      0.0    0.258199  ...   
Jumanji                                        0.0    0.000000  ...   
Grumpier Old Men                               0.5    0.408248  ...   
Father of the Bride Part II                    0.0    0.577350  ...   
Sabrina                                        0.5    0.408248  ...   

title                        Blade Runner 2049  Mother!  \
title                                                     
Toy Story                                  0.0      0.0   
Jumanji                                    0.0      0.0   
Grumpier Old Men                           0.0      0.0   
Father of the Bride Part II                0.0      0.0   
Sabrina                                    0.0      0.0   

title                        Jumanji: Welcome to the Jungle  \
title                                                         
Toy Story                                          0.516398   
Jumanji                                            0.666667   
Grumpier Old Men                                   0.000000   
Father of the Bride Part II                        0.000000   
Sabrina                                            0.000000   

title                        The Shape of Water  The Greatest Showman  \
title                                                                   
Toy Story                              0.516398                   0.0   
Jumanji                                0.666667                   0.0   
Grumpier Old Men                       0.000000                   0.0   
Father of the Bride Part II            0.000000                   0.0   
Sabrina                                0.000000                   0.0   

title                        Game Night  Tomb Raider  Deadpool 2  \
title                                                              
Toy Story                      0.223607     0.516398    0.258199   
Jumanji                        0.000000     0.666667    0.000000   
Grumpier Old Men               0.353553     0.000000    0.408248   
Father of the Bride Part II    0.500000     0.000000    0.577350   
Sabrina                        0.353553     0.000000    0.408248   

title                        Solo: A Star Wars Story  Gintama: The Movie  
title                                                                     
Toy Story                  

## 쓰리 닷..?

In [50]:

# 'runtime' 열을 2차원 배열로 만들기
runtime_array = data['runtime'].values.reshape(-1, 1)

# 모든 정보를 합쳐서 2차원 배열 만들기
combined_array = np.hstack([genres_array, runtime_array, tag_array])

# 코사인 유사도 계산
cosine_sim_genre_runtime_tag = cosine_similarity(combined_array, combined_array)

# 유사도 행렬 출력
print(cosine_sim_genre_runtime_tag)

[[1.         0.35607317 0.37911854 ... 0.28856514 0.34856747 0.17548313]
 [0.35607317 1.         0.54334834 ... 0.21563412 0.5188273  0.39859486]
 [0.37911854 0.54334834 1.         ... 0.21350723 0.17734487 0.39415536]
 ...
 [0.28856514 0.21563412 0.21350723 ... 1.         0.48888959 0.36659427]
 [0.34856747 0.5188273  0.17734487 ... 0.48888959 1.         0.56754319]
 [0.17548313 0.39859486 0.39415536 ... 0.36659427 0.56754319 1.        ]]


In [51]:
# 영화-영화 유저관람 내역에 대한 유사도
movie_similarity_genre_runtime_tag = pd.DataFrame(cosine_sim_genre_runtime_tag,
                                index=title, columns=title)
print(movie_similarity_genre_runtime_tag.shape)
movie_similarity_genre_runtime_tag.head()

(1572, 1572)


title                        Toy Story   Jumanji  Grumpier Old Men  \
title                                                                
Toy Story                     1.000000  0.356073          0.379119   
Jumanji                       0.356073  1.000000          0.543348   
Grumpier Old Men              0.379119  0.543348          1.000000   
Father of the Bride Part II   0.292372  0.358985          0.409599   
Sabrina                       0.353336  0.500205          0.533757   

title                        Father of the Bride Part II   Sabrina  \
title                                                                
Toy Story                                       0.292372  0.353336   
Jumanji                                         0.358985  0.500205   
Grumpier Old Men                                0.409599  0.533757   
Father of the Bride Part II                     1.000000  0.892971   
Sabrina                                         0.892971  1.000000   

title                        American President, The     Nixon    Casino  \
title                                                                      
Toy Story                                   0.416687  0.388825  0.493891   
Jumanji                                     0.393996  0.402439  0.405803   
Grumpier Old Men                            0.345059  0.240991  0.254723   
Father of the Bride Part II                 0.346070  0.301933  0.483012   
Sabrina                                     0.446822  0.321239  0.501522   

title                        Sense and Sensibility  Get Shorty  ...  \
title                                                           ...   
Toy Story                                 0.294102    0.460730  ...   
Jumanji                                   0.335026    0.397688  ...   
Grumpier Old Men                          0.439442    0.539083  ...   
Father of the Bride Part II               0.322683    0.686609  ...   
Sabrina                                   0.347512    0.679717  ...   

title                        Blade Runner 2049   Mother!  \
title                                                      
Toy Story                             0.493098  0.414974   
Jumanji                               0.367483  0.455167   
Grumpier Old Men                      0.199405  0.258500   
Father of the Bride Part II           0.156012  0.247402   
Sabrina                               0.286024  0.307728   

title                        Jumanji: Welcome to the Jungle  \
title                                                         
Toy Story                                          0.466817   
Jumanji                                            0.192876   
Grumpier Old Men                                   0.189682   
Father of the Bride Part II                        0.318618   
Sabrina                                            0.200768   

title                        The Shape of Water  The Greatest Showman  \
title                                                                   
Toy Story                              0.376448              0.514366   
Jumanji                                0.547531              0.419842   
Grumpier Old Men                       0.265138              0.490794   
Father of the Bride Part II            0.274051              0.214217   
Sabrina                                0.393441              0.260358   

title                        Game Night  Tomb Raider  Deadpool 2  \
title                                                              
Toy Story                      0.389748     0.372103    0.288565   
Jumanji                        0.188197     0.738430    0.215634   
Grumpier Old Men               0.435960     0.499202    0.213507   
Father of the Bride Part II    0.472344     0.327526    0.565361   
Sabrina                        0.370924     0.395905    0.436438   

title                        Solo: A Star Wars Story  Gintama: The Movie  
title                                                       